### ISSUE TITLE
I pressed make run and nothing happened using the latest release

### ISSUE THREAD

**Issue by wadbr** [seonglae/intuiter#21]
Hello! 

So how can I make the ahk script run? 

Also would it be possible to run the feature with CapsLock being down instead of alt?

**Comment by seonglae** [comment]
![image](https://user-images.githubusercontent.com/27716524/121208843-55db4000-c8b5-11eb-88d4-f62b7d2a49cb.png)

If you press button, the program starts and you can see ahk program in system tray

**Comment by seonglae** [comment]
Alt or Capslock for Magic Key option is great Idea.

I checked feasibility of idea and I'll update it soon

Maybe that option will be selectable in UI

**Comment by wadbr** [comment]
after restart works now thank you! 

awesome app <3
